# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/HADIRAYANEH/PASSWORD_GENERATOR/UI/GEN.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_generator(object):
    def setupUi(self, generator):
        generator.setObjectName("generator")
        generator.resize(1124, 865)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        generator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(generator)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1121, 831))
        self.frame.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(180, 80, 941, 751))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(440, 340, 441, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Pictures/Two factor authentication-amico.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 360, 391, 391))
        self.frame_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 321, 254))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(18)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(16)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(30, 30))
        self.checkBox.setAutoRepeatDelay(300)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(16)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(16)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setGeometry(QtCore.QRect(140, 10, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0;")
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(120, 320, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);\n"
"border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(100, 90, 711, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.copy = QtWidgets.QPushButton(self.frame_2)
        self.copy.setGeometry(QtCore.QRect(800, 180, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.copy.setFont(font)
        self.copy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-radius:15px;")
        self.copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Pictures/icons8-copy-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy.setIcon(icon)
        self.copy.setIconSize(QtCore.QSize(50, 50))
        self.copy.setObjectName("copy")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(70, 180, 731, 71))
        font = QtGui.QFont()
        font.setFamily("Raleway SemiBold")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(0,255, 255);\n"
"border-radius:15px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1121, 71))
        self.frame_4.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border-radius:15px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.close = QtWidgets.QPushButton(self.frame_4)
        self.close.setGeometry(QtCore.QRect(1080, 10, 31, 28))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius:8px;")
        self.close.setText("")
        self.close.setObjectName("close")
        self.min = QtWidgets.QPushButton(self.frame_4)
        self.min.setGeometry(QtCore.QRect(1040, 10, 31, 28))
        self.min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.min.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"border-radius:8px;")
        self.min.setText("")
        self.min.setObjectName("min")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Pictures/icons8-generator-68.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 260, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(17)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:0;")
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 80, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(17)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setToolTip("")
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:0;")
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 170, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway")
        font.setPointSize(17)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setToolTip("")
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:0;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Downloads/icons8-setting-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 800, 131, 20))
        self.label_5.setStyleSheet("background-color: rgb(112, 112, 167)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 770, 101, 20))
        self.label_9.setStyleSheet("background-color: rgb(112, 112, 167)")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 740, 51, 20))
        self.label_10.setStyleSheet("background-color: rgb(112, 112, 167)")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        generator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(generator)
        self.statusbar.setObjectName("statusbar")
        generator.setStatusBar(self.statusbar)

        self.retranslateUi(generator)
        self.min.clicked.connect(generator.showMinimized)
        self.close.clicked.connect(generator.close)
        QtCore.QMetaObject.connectSlotsByName(generator)

    def retranslateUi(self, generator):
        _translate = QtCore.QCoreApplication.translate
        generator.setWindowTitle(_translate("generator", "MainWindow"))
        self.checkBox_3.setToolTip(_translate("generator", "Numbers=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)"))
        self.checkBox_3.setText(_translate("generator", "Number"))
        self.checkBox_4.setToolTip(_translate("generator", "Symbols=(!@#$%^&*?)"))
        self.checkBox_4.setText(_translate("generator", "Symbols"))
        self.checkBox.setToolTip(_translate("generator", "Uppercase characters=(ABCDEFGH...)"))
        self.checkBox.setText(_translate("generator", "Uppercase characters"))
        self.checkBox_2.setToolTip(_translate("generator", "Lowercase characters=(abcdefgh...)"))
        self.checkBox_2.setText(_translate("generator", "Lowercase characters"))
        self.checkBox_5.setToolTip(_translate("generator", "Ambiguous characters=( [] () / \" : )"))
        self.checkBox_5.setText(_translate("generator", "Ambiguous characters"))
        self.label_3.setText(_translate("generator", "Length:"))
        self.pushButton.setText(_translate("generator", "generate"))
        self.label_2.setText(_translate("generator", "instantly create a secure, random Password"))
        self.copy.setToolTip(_translate("generator", "copy"))
        self.label_4.setText(_translate("generator", "Generator"))
        self.close.setToolTip(_translate("generator", "close"))
        self.min.setToolTip(_translate("generator", "minimize"))
        self.label_7.setText(_translate("generator", "GENERATOR"))
        self.pushButton_2.setText(_translate("generator", "About Alan"))
        self.pushButton_4.setText(_translate("generator", "Home"))
        self.pushButton_3.setText(_translate("generator", "Setting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    generator = QtWidgets.QMainWindow()
    ui = Ui_generator()
    ui.setupUi(generator)
    generator.show()
    sys.exit(app.exec_())

